### ISSUE TITLE
Gradle link

### ISSUE THREAD

**Issue by 3ffusi0on** [TouchBoarder/weekdays-buttons-bar#1]
The gradle dependencies cannot be resolved.

> compile 'com.github.touchboarder:weekdays-buttons-bar:v0.2-alpha'

**Comment by TouchBoarder** [comment]
And you have included "https://jitpack.io" dependencies?

**Comment by 3ffusi0on** [comment]
This isn't enough ?

> dependencies {
>      compile 'com.github.touchboarder:weekdays-buttons-bar:v0.2-alpha'
> }

**Comment by TouchBoarder** [comment]
Please look at the link I provided, first you need to add the jitpack repository in the root build.gradle file as explained (the one located in the same folder as the settings.gradle file). Then you can add the dependencies for the library like you posted in the root/project build.gradle file.

**Comment by 3ffusi0on** [comment]
You're right, that's my bad there. Never had to do like this before. Thank you for the help.

Nice repo btw ;-)
