### ISSUE TITLE
disable all elements at once

### ISSUE THREAD

**Issue by vipulasri** [TouchBoarder/weekdays-buttons-bar#8]
option/method to disable weekdays view and re-enable it.

**Comment by TouchBoarder** [comment]
weekdaysDataSource.selectAll(true/false)

weekdaysDataSource.setSelectedDays(Calendar.MONDAY, Calendar.WEDNESDAY);

weekdaysDataSource..setSelectedDays(int[2,3,4])//Use an array with Calendar class constants like Calendar.MONDAY

Check out the sample code for how to implement W-B-B in various ways https://github.com/TouchBoarder/weekdays-buttons-bar/blob/master/sample/src/main/java/com/touchboarder/weekdaysdemo/MainActivity.java
